baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Francisco Bicho'
theme = "chringel-hugo-theme"

copyright = "© 2023 Copyright Francisco Bicho"

pluralizelisttitles = false
paginate = 10
enableEmoji = true

[Params]
    name = "chringel"
    description = "A privacy focused theme for Hugo"

    github_user = "chringel21"
    github_repo = "https://github.com/chringel21/chringel-hugo-theme"
    github_banner = true

    favicon = "favicon.ico"

    # Title to be displayed in header
    headerTitle = 'Francisco Bicho'
    # User image
    #titleImage = 'images/index.png'
    # Copyright text displayed in footer
    footerCopyrightText = '© 2023 Copyright Francisco Bicho'

# Favicons config
# Get your favicons from https://realfavicongenerator.net/
# Put them in the 'static' folder
[Params.favicons]
  msApplicationTileColor = '#5bbad5'
  themeColor = '#ffffff'


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
